BazarNetCore/Models/ProdactType.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BazarNetCore.Models
{
    public class ProdactType
    {
        public int id { get; set; }
        public string Name { get; set; }
    }
}

BazarNetCore/Models/Prodacts.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BazarNetCore.Models
{
    public class Prodacts
    {
        public int id { get; set; }
        public string Name { get; set; }
        public string Salers { get; set; }
        public string ProdactType { get; set; }
        public string Weight { get; set; }
        public int Count { get; set; }
        public int Price { get; set; }
        public byte[] Image { get; set; }
        public string ImageMimeTypeOfData { get; set; }
    }
}

BazarNetCore/Controllers/ProdactTypesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BazarNetCore.Data;
using BazarNetCore.Models;

namespace BazarNetCore.Controllers
{
    public class ProdactTypesController : Controller
    {
        private readonly ApplicationContex _context;

        public ProdactTypesController(ApplicationContex context)
        {
            _context = context;
        }

        // GET: ProdactTypes
        public async Task<IActionResult> Index()
        {
            return View(await _context.ProdactTypes.ToListAsync());
        }

        // GET: ProdactTypes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var prodactType = await _context.ProdactTypes
                .FirstOrDefaultAsync(m => m.id == id);
            if (prodactType == null)
            {
                return NotFound();
            }

            return View(prodactType);
        }

        // GET: ProdactTypes/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: ProdactTypes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("id,Name")] ProdactType prodactType)
        {
            if (ModelState.IsValid)
            {
                _context.Add(prodactType);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(prodactType);
        }

        // GET: ProdactTypes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var prodactType = await _context.ProdactTypes.FindAsync(id);
            if (prodactType == null)
            {
                return NotFound();
            }
            return View(prodactType);
        }

        // POST: ProdactTypes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("id,Name")] ProdactType prodactType)
        {
            if (id != prodactType.id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(prodactType);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProdactTypeExists(prodactType.id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(prodactType);
        }

        // GET: ProdactTypes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var prodactType = await _context.ProdactTypes
                .FirstOrDefaultAsync(m => m.id == id);
            if (prodactType == null)
            {
                return NotFound();
            }

            return View(prodactType);
        }

        // POST: ProdactTypes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var prodactType = await _context.ProdactTypes.FindAsync(id);
            _context.ProdactTypes.Remove(prodactType);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ProdactTypeExists(int id)
        {
            return _context.ProdactTypes.Any(e => e.id == id);
        }
    }
}

BazarNetCore/Controllers/ProdactsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BazarNetCore.Data;
using BazarNetCore.Models;
using Microsoft.AspNetCore.Http;
using System.IO;

namespace BazarNetCore.Controllers
{
    public class ProdactsController : Controller
    {
        private readonly ApplicationContex _context;

        public ProdactsController(ApplicationContex context)
        {
            _context = context;
        }


        public async Task<IActionResult> AddImage(int? id, IFormFile uploads)
        {
            if (id != null)
                if (uploads != null)
                {
                    Prodacts prodacts = await _context.Prodacts.Where(x => x.id == id).FirstOrDefaultAsync();
                    byte[] p1 = null;
                    using (var fs1 = uploads.OpenReadStream())
                    using (var ms1 = new MemoryStream())
                    {
                        fs1.CopyTo(ms1);
                        p1 = ms1.ToArray();
                    }
                    prodacts.ImageMimeTypeOfData = uploads.ContentType;
                    prodacts.Image = p1;
                    _context.Prodacts.Update(prodacts);
                    _context.SaveChanges();
                    return RedirectToAction(nameof(Index));
                }

            return RedirectToAction(nameof(Index));
        }

        public IActionResult AddImageForm(int? id)
        {
            Prodacts prodacts;
            if (id == null)
            {
                return NotFound();
            }

            prodacts = _context.Prodacts.Where(x => x.id == id).FirstOrDefault();
            if (prodacts == null)
            {
                return NotFound();
            }
            return View(prodacts);
        }

        public FileContentResult GetImage(int id)
        {
            Prodacts prodacts = _context.Prodacts
                .FirstOrDefault(g => g.id == id);

            if (prodacts != null)
            {
                var file = File(prodacts.Image, prodacts.ImageMimeTypeOfData);
                return file;
            }
            else
            {
                return null;
            }
        }
        // GET: Prodacts
        public async Task<IActionResult> Index()
        {
            return View(await _context.Prodacts.ToListAsync());
        }

        // GET: Prodacts/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var prodacts = await _context.Prodacts
                .FirstOrDefaultAsync(m => m.id == id);
            if (prodacts == null)
            {
                return NotFound();
            }

            return View(prodacts);
        }

        // GET: Prodacts/Create
        public IActionResult Create()
        {
            SelectList salers = new SelectList(_context.Salers.Select(x => x.Name).ToList());
            ViewBag.salers = salers;
            SelectList types = new SelectList(_context.ProdactTypes.Select(x => x.Name).ToList());
            ViewBag.types = types;
            return View();
        }

        // POST: Prodacts/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("id,Name,Salers,ProdactType, Weight, Count, Price")] Prodacts prodacts)
        {
            if (ModelState.IsValid)
            {
                _context.Add(prodacts);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(prodacts);
        }

        // GET: Prodacts/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var prodacts = await _context.Prodacts.FindAsync(id);
            if (prodacts == null)
            {
                return NotFound();
            }
            SelectList salers = new SelectList(_context.Salers.Select(x => x.Name).ToList());
            ViewBag.salers = salers;
            SelectList types = new SelectList(_context.ProdactTypes.Select(x => x.Name).ToList());
            ViewBag.types = types;
            return View(prodacts);
        }

        // POST: Prodacts/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("id,Name,Salers,ProdactType, Weight, Count, Price")] Prodacts prodacts)
        {
            if (id != prodacts.id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(prodacts);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProdactsExists(prodacts.id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(prodacts);
        }

        // GET: Prodacts/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var prodacts = await _context.Prodacts
                .FirstOrDefaultAsync(m => m.id == id);
            if (prodacts == null)
            {
                return NotFound();
            }

            return View(prodacts);
        }

        // POST: Prodacts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var prodacts = await _context.Prodacts.FindAsync(id);
            _context.Prodacts.Remove(prodacts);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ProdactsExists(int id)
        {
            return _context.Prodacts.Any(e => e.id == id);
        }
    }
}

BazarNetCore/Views/Prodacts/AddImageForm.cshtml
@model BazarNetCore.Models.Prodacts
@{
    ViewData["Title"] = "AddImageForm";
}

<h1>AddImageForm</h1>

<form asp-controller="Prodacts" asp-action="AddImage" method="post" enctype="multipart/form-data">
    <input asp-for="id" readonly class="control-label"></input>
    <input type="file" name="uploads" /><br>
    <input type="submit" value="Загрузить" class="btn btn-primary" />
</form>

BazarNetCore/Views/Prodacts/Create.cshtml
@model BazarNetCore.Models.Prodacts

@{
    ViewData["Title"] = "Создать";
}

<h1>Create</h1>

<h4>Prodacts</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                @Html.DisplayName("Название")
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                @Html.DisplayName("Продавцы")
                @Html.DropDownList("Salers", ViewBag.salers as SelectList, htmlAttributes: new { @class = "form-control" })
                <span asp-validation-for="Salers" class="text-danger"></span>
                <a class="btn btn-success" target="_blank" asp-controller="Salers" asp-action="Create">Добавить продавца</a>
            </div>
            <div class="form-group">
                @Html.DisplayName("Тип")
                @Html.DropDownList("ProdactType", ViewBag.types as SelectList, htmlAttributes: new { @class = "form-control" })
                <span asp-validation-for="ProdactType" class="text-danger"></span>
                <a class="btn btn-success" target="_blank" asp-controller="ProdactTypes" asp-action="Create">Добавить тип продукта</a>
            </div>
            <div class="form-group">
                @Html.DisplayName("Колличество")
                <input asp-for="Count" class="form-control" />
                <span asp-validation-for="Count" class="text-danger"></span>
            </div>
            <div class="form-group">
                @Html.DisplayName("Вес")
                <input asp-for="Weight" class="form-control" />
                <span asp-validation-for="Weight" class="text-danger"></span>
            </div>
            <div class="form-group">
                @Html.DisplayName("Цена")
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

BazarNetCore/Views/Prodacts/Delete.cshtml
@model BazarNetCore.Models.Prodacts

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Prodacts</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Salers)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Salers)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ProdactType)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ProdactType)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

BazarNetCore/Views/Prodacts/Details.cshtml
@model BazarNetCore.Models.Prodacts

@{
    ViewData["Title"] = "Details";
}

<h1>@Model.Salers @Model.Name</h1>

<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Salers)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Salers)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ProdactType)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ProdactType)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

BazarNetCore/Views/Prodacts/Edit.cshtml
@model BazarNetCore.Models.Prodacts

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Prodacts</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="id" />
            <div class="form-group">
                @Html.DisplayName("Название")
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                @Html.DisplayName("Продавцы")
                @Html.DropDownList("Salers", ViewBag.salers as SelectList, htmlAttributes: new { @class = "form-control" })
                <span asp-validation-for="Salers" class="text-danger"></span>
                <a class="btn btn-success" target="_blank" asp-controller="Salers" asp-action="Create">Добавить продавца</a>
            </div>
            <div class="form-group">
                @Html.DisplayName("Тип")
                @Html.DropDownList("ProdactType", ViewBag.types as SelectList, htmlAttributes: new { @class = "form-control" })
                <span asp-validation-for="ProdactType" class="text-danger"></span>
                <a class="btn btn-success" target="_blank" asp-controller="ProdactTypes" asp-action="Create">Добавить тип продукта</a>
            </div>
            <div class="form-group">
                @Html.DisplayName("Колличество")
                <input asp-for="Count" class="form-control" />
                <span asp-validation-for="Count" class="text-danger"></span>
            </div>
            <div class="form-group">
                @Html.DisplayName("Вес")
                <input asp-for="Weight" class="form-control" />
                <span asp-validation-for="Weight" class="text-danger"></span>
            </div>
            <div class="form-group">
                @Html.DisplayName("Цена")
                <input asp-for="Price" class="form-control" />
                <span a
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

BazarNetCore/Views/Prodacts/Index.cshtml
@model IEnumerable<BazarNetCore.Models.Prodacts>

@{
    ViewData["Title"] = "Товары";
}

<h1>Товары</h1>

<p>
    <a class="btn btn-info" asp-action="Create">Create New</a>
</p>

@foreach (var item in Model)
{
<div>
    <div>@Html.DisplayName("Название: ") @Html.DisplayName(item.Name)</div>
    <div>@Html.DisplayName("Колличество: ") @Html.DisplayName(item.Count.ToString())</div>
    <div>@Html.DisplayName("Тип: ") @Html.DisplayName(item.ProdactType)</div>
    <div>@Html.DisplayName("Вес: ") @Html.DisplayName(item.Weight.ToString())</div>
    <div>@Html.DisplayName("Цена: ") @Html.DisplayName(item.Price.ToString() + "Грн")</div>
    <div class="img">
        @if (item.Image == null)
        {
            
        }
        else
        {
            <img class="img-thumbnail" width="350" height="250"
                 src="@Url.Action("GetImage", "Prodacts",
                        new { item.id })" />
        }
    </div>
    <div>
        <a class="btn btn-success" asp-action="Details" asp-route-id="@item.id">Детали</a>
        <a class="btn btn-success" asp-action="AddImageForm" asp-route-id="@item.id">Добавить картинку</a>
        <a class="btn btn-info" asp-action="Edit" asp-route-id="@item.id">Редактировать</a>
        <a class="btn btn-danger" asp-action="Delete" asp-route-id="@item.id">Удалить</a>
    </div>
</div>
}